ARG PYTHON_BASE_IMAGE=harbor.szistech.com/docker.io/python:3.11-bullseye
FROM ${PYTHON_BASE_IMAGE}

ENV SOAR_VERSION 0.11.0
ENV TZ Asia/Shanghai

ARG HTTPS_PROXY=""
ARG HTTP_PROXY=""
WORKDIR /opt

COPY setup.sh /opt/setup.sh
RUN chmod +x /opt/setup.sh \
    && /opt/setup.sh \
    && rm -rf /opt/setup.sh

